# Generated by Django 6.0.4 on 2026-04-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('method_type', models.CharField(choices=[('CARD', 'Tarjeta'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia')], max_length=20, verbose_name='Tipo de Método')),
                ('details', models.TextField(blank=True, verbose_name='Detalles/Instrucciones')),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_methods/', verbose_name='Imagen/Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
