# Generated by Django 6.0.4 on 2026-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_methods/'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CARD', 'Tarjeta de Crédito/Débito'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia/Pago Móvil')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
