# Generated by Django 6.0.4 on 2026-05-02 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_data_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='method_type',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='payments.currency'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='payments.paymenttype'),
        ),
    ]
