# Generated by Django 6.0.4 on 2026-04-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='representative',
            field=models.ForeignKey(blank=True, help_text='El representante de este estudiante (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COACH', 'Entrenador'), ('REPRESENTATIVE', 'Representante'), ('STUDENT', 'Estudiante')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
