# Generated by Django 6.0.4 on 2026-05-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identification',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
