# Generated by Django 6.0.4 on 2026-05-12 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Plan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('strikethrough_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio Tachado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='¿Es Promoción?')),
                ('requires_inscription', models.BooleanField(default=False, verbose_name='Requiere Inscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Activo')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título del Requisito')),
                ('content', models.TextField(verbose_name='Contenido (Soporta Markdown)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Activo')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descripción de la Característica')),
                ('is_included', models.BooleanField(default=True, verbose_name='¿Incluido?')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plans.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Característica de Plan',
                'verbose_name_plural': 'Características de Planes',
            },
        ),
    ]
